# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
#
# For full config options, check the docs:
#    docs.serverless.com

service: build-ordr-from-po-and-notify

plugins:
  - serverless-dotenv-plugin

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: us-west-2

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  service:
    handler: bin/service
    description: POST webhook to build sale order from purchase order and notify via email
    events:
      - http:
          path: zauru/build-order-from-purchase-order-and-notify
          method: post