service: get-due-clients-send-pymnt-req

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  timeout: 30 # optional, in seconds, default is 6
  memorySize: 128 # Overwrite the default memory size. Default is 1024

functions:
  send-mail:
    handler: bin/send-mail
    events:
      - http:
          path: send-mail
          method: get

package:
 exclude:
   - ./**
 include:
   - ./bin/**
